In [4]:
import pandas as pd

# from pandas import Series, DataFrame




row_of_data = [10,20,30,40]
cols= ["Nate", "Rebecca", "Edwin", "Preston"]
series_of_data = pd.Series(row_of_data, index=cols)
print(f"list: {row_of_data}")
print(f"series: \n{series_of_data}")

list: [10, 20, 30, 40]
series:
Nate       10
Rebecca    20
Edwin      30
Preston    40
dtype: int64

In [12]:
# DataFrame By column

family = {
    "name": ["nate", "rebecc", "edwin", "preston"],
    "age": [40, 41, 12, 8]
}
df1 = pd.DataFrame(data=family, index=family["name"])
df1

            name  age
nate        nate   40
rebecc    rebecc   41
edwin      edwin   12
preston  preston    8

In [15]:
# DataFrame by Rows
cols1 = ["name", "age"]
rows = [
    ["nate", 40],
    ["rebecca", 41],
    ["edwin", 12],
    ["preston", 8],
]
df2 = pd.DataFrame(data=rows, columns=cols1)
df2

      name  age
0     nate   40
1  rebecca   41
2    edwin   12
3  preston    8

In [24]:
df1["age"]["nate"]

np.int64(40)

In [25]:
df2["name"][1]

'rebecca'

In [26]:
df2["gender"] = ["M", "F", "M", "M"]
df2

      name  age gender
0     nate   40      M
1  rebecca   41      F
2    edwin   12      M
3  preston    8      M

In [27]:
df2[["name", "gender"]]

      name gender
0     nate      M
1  rebecca      F
2    edwin      M
3  preston      M

In [28]:
df2.columns

Index(['name', 'age', 'gender'], dtype='str')

In [30]:
df2.head(2)

      name  age gender
0     nate   40      M
1  rebecca   41      F

In [ ]:
df2.isnull().sum()

name      0.0
age       0.0
gender    0.0
dtype: float64

In [35]:
df2.describe()

             age
count   4.000000
mean   25.250000
std    17.689451
min     8.000000
25%    11.000000
50%    26.000000
75%    40.250000
max    41.000000

In [41]:
df1.sort_index(ascending=False, inplace=True)

In [43]:
df1 = df1.sort_values(["age"])

In [44]:
df1

            name  age
preston  preston    8
edwin      edwin   12
nate        nate   40
rebecc    rebecc   41

In [46]:
df2 = df2.rename(columns={"age": "a"})
df2

      name   a gender
0     nate  40      M
1  rebecca  41      F
2    edwin  12      M
3  preston   8      M

In [51]:
df2.loc[0]

name      nate
a           40
gender       M
Name: 0, dtype: object

In [52]:
df2.loc[0,"a"]

np.int64(40)

In [54]:
df2.loc[0,"a"] = 39
df2

      name   a gender
0     nate  39      M
1  rebecca  41      F
2    edwin  12      M
3  preston   8      M

In [56]:
df1.loc["nate", "age"]

np.int64(40)

In [58]:
df1.iloc[0,1]

np.int64(8)

In [61]:
df1 = df1.reset_index()

In [70]:
df1.drop(labels=["index"], axis=1)

      name  age
0  preston    8
1    edwin   12
2     nate   40
3   rebecc   41

In [73]:
df2.at[0, "a"]

np.int64(39)

In [75]:
df2.iat[1,1] = 39

In [76]:
df2

      name   a gender
0     nate  39      M
1  rebecca  39      F
2    edwin  12      M
3  preston   8      M

In [77]:
df2.loc[0:3, "name"]

0       nate
1    rebecca
2      edwin
3    preston
Name: name, dtype: str

In [78]:
df2.loc[:,"name"]

0       nate
1    rebecca
2      edwin
3    preston
Name: name, dtype: str

In [79]:
df2.loc[df2["a"]>=18]

      name   a gender
0     nate  39      M
1  rebecca  39      F

In [80]:
df2.loc[df2["a"]>=18, "name"]

0       nate
1    rebecca
Name: name, dtype: str

In [81]:
df2["is_adult"] = False
df2

      name   a gender  is_adult
0     nate  39      M     False
1  rebecca  39      F     False
2    edwin  12      M     False
3  preston   8      M     False

In [82]:
df2.loc[df2["a"] >= 18, "is_adult"] = True
df2

      name   a gender  is_adult
0     nate  39      M      True
1  rebecca  39      F      True
2    edwin  12      M     False
3  preston   8      M     False

In [ ]:
df2.to_csv("")