- loops
- rename
- apply
- aggregate

In [43]:
import pandas as pd

# data = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/french-ambs.csv"
# df = pd.read_csv(data)
# df.head()

In [44]:
# ./filename.csv call path at current folder.filename.csv
# ../ => goes back one folder
# df.to_csv("../data/french-ambs.csv", index=False)

In [45]:
df = pd.read_csv("../data/french-ambs.csv")
df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [46]:
df = df.drop(columns=["lat_long"])
df.head()

   id                name    place  year    lat   long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57

In [47]:
df = df[["name", "place", "year"]]
df.head()

                 name    place  year
0  Richer, Christophe  Denmark  1543
1  Richer, Christophe  Denmark  1541
2  Danzay, Charles de  Denmark  1561
3  Danzay, Charles de  Denmark  1563
4  Danzay, Charles de  Denmark  1582

In [48]:
df["place"].unique()

<StringArray>
[          'Denmark',           'England',            'Geneva',
           'Grisons', 'Holy Roman Empire',       'Netherlands',
    'Ottoman Empire',          'Portugal',              'Rome',
          'Scotland',             'Spain',     'Swiss Cantons',
            'Venice',            'Poland',             'Savoy',
           'Ferrara',            'Saxony',           'Tuscany']
Length: 18, dtype: str

In [49]:
df["place"].count()
df["place"].nunique()

18

In [50]:
# Loops
# iterrows / itertuples
# iterrows
for idx, row in df.iterrows():
    if row["place"] == "Holy Roman Empire":
        df.at[idx, "place"] = "HRE"

df["place"].unique()

<StringArray>
[       'Denmark',        'England',         'Geneva',        'Grisons',
            'HRE',    'Netherlands', 'Ottoman Empire',       'Portugal',
           'Rome',       'Scotland',          'Spain',  'Swiss Cantons',
         'Venice',         'Poland',          'Savoy',        'Ferrara',
         'Saxony',        'Tuscany']
Length: 18, dtype: str

In [51]:
for row in df.itertuples():
    idx = row.Index
    if row.place == "Ottoman Empire":
        df.at[idx,"place"] = "Ott"

df["place"].unique()

<StringArray>
[      'Denmark',       'England',        'Geneva',       'Grisons',
           'HRE',   'Netherlands',           'Ott',      'Portugal',
          'Rome',      'Scotland',         'Spain', 'Swiss Cantons',
        'Venice',        'Poland',         'Savoy',       'Ferrara',
        'Saxony',       'Tuscany']
Length: 18, dtype: str

In [52]:
# using .loc to replace

df.loc[df["place"] == "Netherlands", "place"] = "Neth"
df["place"].unique()

<StringArray>
[      'Denmark',       'England',        'Geneva',       'Grisons',
           'HRE',          'Neth',           'Ott',      'Portugal',
          'Rome',      'Scotland',         'Spain', 'Swiss Cantons',
        'Venice',        'Poland',         'Savoy',       'Ferrara',
        'Saxony',       'Tuscany']
Length: 18, dtype: str

In [53]:
# replace many with a  hash using .replace
hash = {place: f"{place[:3] + '.' if len(place) > 4 else place}"  for place in df["place"].unique()}
df["place"] = df["place"].replace(hash)

In [54]:
df["place"].unique()

<StringArray>
['Den.', 'Eng.', 'Gen.', 'Gri.',  'HRE', 'Neth',  'Ott', 'Por.', 'Rome',
 'Sco.', 'Spa.', 'Swi.', 'Ven.', 'Pol.', 'Sav.', 'Fer.', 'Sax.', 'Tus.']
Length: 18, dtype: str

In [55]:
# complicated boolean logic with | (or), & (and), ~ (not)
df.loc[((df["place"] == "Netherlands") | (df["place"] == "England")) & (df["year"] < 1550)]

Empty DataFrame
Columns: [name, place, year]
Index: []

In [56]:
df.loc[~((df["place"] == "Netherlands") | (df["place"] == "England")) & (df["year"] < 1550)]

                         name place  year
0          Richer, Christophe  Den.  1543
1          Richer, Christophe  Den.  1541
5          Bapaume, Robert de  Eng.  1516
6    Passano, Jean-Joachim de  Eng.  1527
7                 De Monpreat  Eng.  1532
..                        ...   ...   ...
854          Daugerant, Louis  Swi.  1537
861          Montluc, Jean de  Ven.  1542
864         Canossa, Louis de  Ven.  1526
866         De Selve, Georges  Ven.  1537
868        Calvimont, Jean de   HRE  1525

[269 rows x 3 columns]

In [ ]:
# .apply() takes a function